name: GCE Deployment

on: push

jobs:
  deploy:
    name: Deployment to Google Compute Engine
    runs-on: ubuntu-latest
    steps:
      - uses: mattes/gce-deploy-action@v5.0.0
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          config: deploy.yml
